language: node_js
node_js:
  - '0.8'
  - '0.10'
env:
  - SASS_VERSION=3.2.12 BOOTCAMP_VERSION=1.0
  - SASS_VERSION=3.3.0.rc.1 BOOTCAMP_VERSION=1.1
before_script:
  - gem update --system
  - gem install sass -v $SASS_VERSION
  - npm install -g grunt-cli
  - npm install bootcamp@$BOOTCAMP_VERSION
